config/routes.rb
Rails.application.routes.draw do


  root 'firstpage#firstpage'

  #root 'articles#index'

  resources :articles
  
  get 'signup', to: 'users#new'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord 
    belongs_to :user
    # this will validate that the title should not be empty
    validates :title, presence: true
    # this will validate that the description should not be empty
    validates :description, presence: true, length: {minimum: 10, maximum: 400}
    # validates the length of title should not be less then 3 and not more than 50
    validates :title, length: {minimum: 3, maximum: 50}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    before_save { self.email = email.downcase }
  
    validates :username, presence: true, 
                         length: { minimum: 3, maximum: 25 },
                         uniqueness: { case_sensitive: false }
  
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                      length: { minimum: 7, maximum: 100 },
                      uniqueness: { case_sensitive: false },
                      format: { with: VALID_EMAIL_REGEX }
    has_secure_password
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def new
        @article = Article.new
    end

    def index
        @articles = Article.all
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was successfully saved"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def create 
        @article = Article.new(article_params)
        @article.user = User.last
        if @article.save
            flash[:notice] = "Article was successfully saved"
            redirect_to articles_path(@article)
        else
            render 'new'
        end
    end

    def show
        @article = Article.find(params[:id])
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path, notice: "Article was successfully deleted."
      end

    private 

    def article_params
        params.require(:article).permit(:title, :description)
    end 

end

app/controllers/firstpage_controller.rb
class FirstpageController < ApplicationController

  def home
  end

  def login
  end

  def signup
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Logged in successfully"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Something went wrong"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end

    private

    def session_params
        params.require(:session).permit(:email, :password)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def index
        @users = User.all
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Account updated successfully"
            redirect_to articles_path(@article)
        else
            render 'edit'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to sigma Blog #{@user.username}"
            redirect_to articles_path(@article)
        else
            render 'new'
        end

    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firstpage_helper.rb
module FirstpageHelper
end

app/views/articles/edit.html.erb
<h1 style="font-family: Arial, sans-serif; color: green">Edit Article</h1>

<%= form_for @article do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title%>
</p>
<p>
    <%= f.label :description %><br>
    <%= f.text_area :description%>
</p>
<p>
<%= f.submit%>
</p>
<% end %>

app/views/articles/index.html.erb
<h1 style="color: green; font-family: Arial, sans-serif">Sigma Blog</h1>

<p style="color: green; font-family: Arial, sans-serif"><%=link_to 'Create new Article', new_article_path %></p>
<p style="color: green; font-family: Arial, sans-serif">
<%= link_to 'All Users', users_path%><br><br>
<%= link_to 'Logout', logout_path, method: :delete%>
</p>
<br>
<hr>
<div style="display: flex; justify-content: center; align-items: center;
  height: 100vh; ">
<table style="color: black; font-family: Arial, sans-serif; border-collapse: separate; border-spacing: 10px; ">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>View</th>
        <th>Edit</th>
        <th>User/ Writer</th>
        <th>Created</th>
        <th>Updated</th>
    </tr>
        <%@articles.each do |article|%>
        <tr>
            <td><%=article.title%></td>
            <td><%=article.description%></td>
            <td><%= link_to 'Show', article_path(article)%></td>
            <td><%= link_to 'Edit', edit_article_path(article)%></td>
            <td><%= article.user.username if article.user%></td>
            <td><%= time_ago_in_words(article.created_at)%> ago</td>
            <td><%= time_ago_in_words(article.created_at)%> ago</td>
        </tr>
        <% end%>
</table>
</div>

app/views/articles/new.html.erb
<h1>Create/Post an Article</h1>

<%= form_for @article do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title%>
</p>
<p>
    <%= f.label :description %><br>
    <%= f.text_area :description%>
</p>
<p>
<%= f.submit%>
</p>
<% end %>

app/views/articles/show.html.erb
<p>
    <%= link_to "All Articles", articles_path%>
</p>
<h3 style="font-family: Arial, sans-serif; color: orange">
    Title: <%= @article.title%>
</h3>


<p style="color: black; font-family: Arial, sans-serif;">
    Description: <%= @article.description%>
</p>
<br>
<hr>
<p>
    Created By: <%= @article.user.username if @article.user%> <br>
    Email: <%= @article.user.email if @article.user%>
    </p>

app/views/firstpage/firstpage.html.erb
<div style="text-align:center;">
<h1>Welcome to My Sigma Blog</h1><br>
<p>Choose an option</p><br>
<%= link_to "Login", login_path, style: "margin:auto;" %><br><br>
<%= link_to "Signup", signup_path, style: "margin:auto;" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SigmaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <ul>
        <li> <%= msg%> </li>
        </ul>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div style="display: flex; justify-content: center;">
<%= form_for @user do |f| %>

<p>
    <%= f.label :username %><br>
    <%= f.text_field :username%>
</p>
<p>
    <%= f.label :email %><br>
    <%= f.email_field :email%>
</p>
<p>
    <%= f.label :password %><br>
    <%= f.password_field :password%>
</p>
<p>
<%= f.submit (@user.new_record? ? "Sign Up": "Update account")%>
</p>
<% end %>
</div>

app/views/users/edit.html.erb
<h1 style="color: green; font-family: Arial, sans-serif">Edit User info</h1>

<%= render 'form'%>

app/views/users/index.html.erb
<h1 style="color: green; font-family: Arial, sans-serif">All Users</h1>


<table style="color: black; font-family: Arial, sans-serif; border-collapse: separate; border-spacing: 30px; ">
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th>No. of Articles</th>
        <th>More</th>
    </tr>
            <%@users.each do |user|%>
        <tr>
            <td><%= user.username%></td>
            <td><%= user.email%></td>
            <td><%= user.articles.count%></td>
            <td><%= link_to 'View', user_path(user)%></td>
        </tr>
            <% end %>
         
    
</table>

app/views/users/new.html.erb
<h1 style="color: green; font-family: Arial, sans-serif">Welcome to Sigma Blog</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 style="color: gray; font-family: Arial, sans-serif">My account</h1>
<p>
    <%= link_to "All Articles", articles_path%>
</p>
<p style="color: black; font-family: Arial, sans-serif;">
    Username: <%= @user.username%>
</p>

<p style="color: black; font-family: Arial, sans-serif;">
    Email: <%= @user.email%>
</p>
<hr>
<h2 style="color: green; font-family: Arial, sans-serif">My Articles</h2><hr>
<table style="color: black; font-family: Arial, sans-serif; border-collapse: separate; border-spacing: 10px; margin: auto;">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>View</th>
        <th>Edit</th>
        <th>Created</th>
        <th>Updated</th>
    <tr>
        <%@user.articles.each do |article|%>
        <tr>
            <td><%=article.title%></td>
            <td><%=article.description%></td>
            <td><%= link_to 'Show', article_path(article)%></td>
            <td><%= link_to 'Edit', edit_article_path(article)%></td>
            <td><%= time_ago_in_words(article.created_at)%> ago</td>
            <td><%= time_ago_in_words(article.created_at)%> ago</td>

        <% end%>
</table>